name: Tests and Build

on:
  pull_request:
    branches:
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests with Coverage on new code
        run: npm run test:cov:changed

      - name: Run e2e Tests
        env:
          PORT: 3001
          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: 5672
          RABBITMQ_USERNAME: guest
          RABBITMQ_PASSWORD: guest
          RABBITMQ_MESSAGE_QUEUE: ws_messages
        run: npm run test:e2e -- --runInBand

      - name: Build Project
        run: npm run build
